Repository swisspost/design-system, pull requests merged in 2023-06, with the labels that each got.

#1478 fix: update installation instructions for v5
  .changeset/fast-carrots-turn.md
  .github/workflows/build-demo.yaml
  .github/workflows/lint.yaml
  .github/workflows/release.yaml
  .github/workflows/unit-tests.yaml
  packages/demo/src/app/home/home.component.html
Labels: release/v5

#1517 fix: add 1px to stickyness-minimal #1156
  .changeset/selfish-nails-stare.md
  packages/internet-header/src/components/post-internet-header/post-internet-header.scss
Labels: open-source-day-june-2023

#1513 fix: add italic defintion to fonts.scss
  .changeset/warm-fireants-deliver.md
  packages/styles/src/components/fonts.scss
Labels: open-source-day-june-2023

#1514 chore: update all storybook links
  .changeset/fair-hats-switch.md
  README.md
  packages/components/cypress/e2e/collapsible.cy.ts
  packages/demo/src/app/app.component.html
  packages/demo/src/app/post-sample/components/icons/icons-demo-page/icons-demo-page.component.html
  packages/documentation/cypress/snapshots/components/collapsible.snapshot.ts
  packages/documentation/cypress/snapshots/internet-header/breadcrumbs.snapshot.ts
  packages/documentation/cypress/snapshots/internet-header/footer.snapshot.ts
  packages/documentation/cypress/snapshots/internet-header/header.snapshot.ts
  packages/documentation/src/stories/icons/components/icon.docs.mdx
  packages/icons/README.md
  packages/internet-header/readme.md
Labels: documentation

#1512 fix: adjust default legend styles sizes
  .changeset/six-bobcats-press.md
  packages/styles/src/components/type.scss
Labels: open-source-day-june-2023
