Repository swisspost/design-system, pull requests merged in 2024-10, with the labels that each got.

#3592 fix(component): fix an issue related to conflicting pointer and focus events hiding the tooltip unexpectedly
  .changeset/red-lies-lick.md
  packages/components/src/components.d.ts
  packages/components/src/components/post-tooltip/post-tooltip.tsx
  packages/components/src/components/post-tooltip/readme.md
Labels: v9

#3525 chore: reset release v7 workflow and set tag "latest-v7" to all publishable package.json files
  .github/workflows/release.yaml
  packages/changelog-github/package.json
  packages/components-angular/projects/components/package.json
  packages/components-react/package.json
  packages/components/package.json
  packages/icons/package.json
  packages/internet-header/package.json
  packages/intranet-header-workspace/projects/intranet-header/package.json
  packages/migrations/package.json
  packages/styles-primeng-workspace/projects/styles-primeng/package.json
  packages/styles/package.json
  packages/tokens/package.json
Labels: v7

#3680 fix(documentation): stop separation of heading and sub heading by screen reader (#3491)
  .changeset/clean-icons-complain.md
  packages/documentation/src/stories/components/heading/heading.stories.ts
Labels: v8

#3681 fix(component): fix an issue related to conflicting pointer and focus events hiding the tooltip unexpectedly (#3592)
  .changeset/red-lies-lick.md
  packages/components/src/components.d.ts
  packages/components/src/components/post-tooltip/post-tooltip.tsx
  packages/components/src/components/post-tooltip/readme.md
  pnpm-lock.yaml
Labels: v8

#3682 chore(documentation): document internet-header configuration setup (#3642)
  packages/documentation/src/stories/getting-started/packages/internet-header/internet-header.docs.mdx
Labels: v8

#3690 fix(documentation): release to netlify
  .changeset/yellow-donkeys-type.md
  .github/actions/setup-netlify-cli/action.yaml
Labels: v8

#3691 fix(documentation): release to netlify
  .changeset/six-wombats-double.md
  .github/actions/setup-netlify-cli/action.yaml
Labels: v7

#3762 chore(intranet-header): fix dropdown nav-link documentation
  .changeset/loud-dingos-remember.md
  packages/documentation/src/stories/components/intranet-header/intranet-header-navigation-bar.sample.html
Labels: v7
