Repository swisspost/design-system, pull requests merged in 2024-09, with the labels that each got.

#3441 feat(docs): add toolbar to switch theme, channel, and mode
  .changeset/empty-islands-kneel.md
  packages/documentation/.storybook/preview.ts
  packages/documentation/.storybook/styles/manager.scss
  packages/documentation/.storybook/styles/preview.scss
  packages/documentation/.storybook/toolbar/index.ts
  packages/documentation/.storybook/toolbar/story-container.ts
Labels: v9

#3502 feat(styles): add tokens get function
  packages/components/package.json
  packages/demo/package.json
  packages/documentation/package.json
  packages/documentation/vite.config.js
  packages/internet-header/package.json
  packages/nextjs-integration/package.json
  packages/styles/gulpfile.js
  packages/styles/package.json
  packages/styles/src/functions/_index.scss
  packages/styles/src/functions/_tokens.scss
  pnpm-lock.yaml
Labels: 🚂 PR train

#3394 chore(styles): Remove deprecated stepper variables
  .changeset/ninety-nails-float.md
  packages/styles/src/variables/components/_stepper.scss
Labels: v9

#3395 chore(styles): Remove deprecated datatable variables
  .changeset/cold-baboons-appear.md
  packages/styles/src/variables/components/_datatable.scss
Labels: v9

#3393 chore(styles): Remove deprecated form-checks variables
  .changeset/heavy-rats-explode.md
  packages/styles/src/variables/components/_form-check.scss
Labels: v9

#3396 fix(styles): Repeating icons in validation messages
  .changeset/great-humans-talk.md
  packages/styles/src/components/form-validation.scss
Labels: v9

#3526 chore: reset release v8 workflow
  .github/workflows/release.yaml
Labels: v8

#3535 chore: restore netlify config for v8
  .github/workflows/release.yaml
  packages/documentation/public/_headers
  packages/documentation/public/_redirects
  packages/documentation/public/assets/versions.json
Labels: v8

#3534 chore: foundations typography heading h1 h6
  .changeset/eleven-keys-work.md
  packages/styles/src/elements/_index.scss
  packages/styles/src/elements/heading.scss
  packages/styles/src/layouts/portal/_type.scss
  packages/styles/src/layouts/portal/index.scss
  packages/styles/src/variables/_heading.scss
  packages/styles/src/variables/_index.scss
Labels: 📦 styles, 🚂 PR train
