Repository swisspost/design-system, pull requests merged in 2024-08, with the labels that each got.

#3387 fix(tag): set max-length to 100%
  .changeset/some-people-say.md
  packages/styles/src/variables/components/_tag.scss
  pnpm-lock.yaml
Labels: v7

#3388 fix(tag): set max-length to 100%
  .changeset/some-people-say.md
  packages/styles/src/variables/components/_tag.scss
Labels: v8

#3366 fix(styles): realign radios / checkboxes labels
  .changeset/fair-kids-cough.md
  packages/styles/src/components/form-check.scss
Labels: v8

#3407 fix(components): replace the componentOnReady method by an helper
  .changeset/serious-games-serve.md
  packages/components/src/components/post-tabs/post-tabs.tsx
  packages/components/src/utils/component-on-ready.ts
  packages/components/src/utils/index.ts
  packages/components/src/utils/tests/component-on-ready.spec.ts
Labels: v8

#3468 chore: align tokens package version with styles package version
  .changeset/config.json
Labels: v8

#3384 chore(docs): removed Monospace font from documentation
  .changeset/gorgeous-flowers-flow.md
  packages/documentation/src/stories/foundation/typography/typography.docs.mdx
Labels: v9

#3345 chore: enter pre-release state for v9
  .changeset/pre.json
  pnpm-lock.yaml
Labels: v9
