Repository swisspost/design-system, pull requests merged in 2024-07, with the labels that each got.

#3049 feat(documentation): add version switch active state to v6
  .changeset/spicy-drinks-relax.md
  packages/documentation/.storybook/addons/version-switcher/VersionSwitcher.tsx
  packages/documentation/.storybook/addons/version-switcher/version-switcher.scss
  packages/documentation/public/netlify.toml
Labels: 🚂 PR train

#2978 feat(styles): invalid message on card-control
  .changeset/giant-bees-sleep.md
  packages/documentation/src/stories/components/forms/card-control/standard-html/card-control.stories.ts
  packages/documentation/src/stories/components/forms/card-control/web-component/card-control.stories.ts
  packages/styles/src/components/form-validation.scss
Labels: 🚂 PR train

#2811 fix: add comment to primeng on table site
  packages/documentation/src/stories/components/table/table.docs.mdx
Labels: 🚂 PR train

#2977 feat(styles): Update buttons colors
  .changeset/funny-tools-scream.md
  packages/documentation/src/stories/components/alert/alert.snapshot.stories.ts
  packages/documentation/src/stories/components/alert/standard-html/alert.stories.ts
  packages/documentation/src/stories/components/alert/web-component/post-alert.stories.ts
  packages/styles/src/components/button.scss
  packages/styles/src/mixins/_color.scss
  packages/styles/src/mixins/_utilities.scss
  packages/styles/src/placeholders/_button.scss
Labels: v7

#3283 feat(styles): build individual components
  .changeset/proud-spies-tap.md
  packages/styles/gulpfile.js
Labels: v7

#3284 chore(styles): update font definitions to remove font weight light
  .changeset/warm-crabs-sit.md
  packages/styles/src/components/intranet-header/_searchbox.scss
  packages/styles/src/components/intranet-header/_top-navigation.scss
  packages/styles/src/layouts/portal/_type.scss
  packages/styles/src/placeholders/_text.scss
  packages/styles/src/variables/_type.scss
  packages/styles/src/variables/components/_accordion.scss
  packages/styles/src/variables/components/_notification.scss
Labels: v7

#3297 fix(workflows): demo release workflow
  .github/workflows/release-demo.yaml
Labels: v7, v8

#3295 chore: update package-manager in package.json
  package.json
  pnpm-lock.yaml
Labels: v7, v9, v8

#3296 chore: update pnpm peerDependencyRules and align primeng angular deps with other packages
  .changeset/rare-sheep-exist.md
  package.json
  packages/styles-primeng-workspace/package.json
  packages/styles-primeng-workspace/projects/styles-primeng/package.json
  pnpm-lock.yaml
Labels: v7

#3243 feat!: update to angular 18
  .changeset/loud-boxes-stare.md
  .changeset/slow-buttons-provide.md
  SECURITY.md
  package.json
  packages/components-angular/angular.json
  packages/components-angular/package.json
  packages/demo/angular.json
  packages/demo/package.json
  packages/demo/src/app/app.module.ts
  packages/demo/src/app/ng-bootstrap/components/datepicker/datepicker-demo-page/datepicker-localization.service.ts
  packages/demo/src/app/ng-bootstrap/components/progressbar/progressbar-demo/progressbar-demo.component.html
  packages/documentation/src/stories/components/datepicker/datepicker-i18n-provider.sample.ts
  packages/documentation/src/stories/getting-started/compatibility/compatibility.docs.mdx
  packages/documentation/src/stories/getting-started/migration-guide/global-state.component.ts
  packages/documentation/src/stories/getting-started/migration-guide/migration-guide.docs.mdx
  packages/documentation/src/stories/getting-started/migration-guide/migrationv7-8.component.ts
  packages/documentation/src/stories/getting-started/migration-guide/setup.component.ts
  packages/intranet-header-workspace/angular.json
  packages/intranet-header-workspace/package.json
  packages/styles-primeng-workspace/angular.json
  packages/styles-primeng-workspace/package.json
  packages/styles-primeng-workspace/projects/styles-primeng/package.json
  packages/styles/package.json
  packages/styles/src/components/pagination.scss
  pnpm-lock.yaml
Labels: v8

#3262 feat(tokens): add `Components/Interactives` and `Components/Notifications` tokens
  .changeset/empty-planets-ring.md
  .changeset/shiny-days-attack.md
  .changeset/thirty-ladybugs-repeat.md
  packages/tokens/tokensstudio-generated/tokens.json
Labels: 🚂 PR train

#3229 feat(styles, documentation): styles update text input
  .changeset/gold-rabbits-train.md
  packages/documentation/src/stories/components/forms/textarea/textarea.stories.ts
  packages/styles/src/components/floating-label.scss
  packages/styles/src/components/form-select.scss
  packages/styles/src/components/form-validation.scss
  packages/styles/src/components/forms.scss
  packages/styles/src/variables/components/_form-select.scss
Labels: v8

#3205 feat(components, components-angular): update the post-collapsible col…
  .changeset/plenty-experts-admire.md
  .changeset/thin-eyes-join.md
  packages/components-angular/projects/consumer-app/src/app/routes/home/home.component.ts
  packages/components/src/components.d.ts
  packages/components/src/components/post-accordion-item/post-accordion-item.tsx
  packages/components/src/components/post-accordion-item/readme.md
  packages/components/src/components/post-collapsible/post-collapsible.tsx
  packages/components/src/components/post-collapsible/readme.md
  packages/documentation/src/stories/components/collapsible/collapsible.stories.ts
Labels: v7

#3265 fix(icons): summary page
  packages/icons/public/index.html
  packages/icons/public/main.js
Labels: v9, v8

#3324 chore: update pnpm-lock
  pnpm-lock.yaml
Labels: v8

#3215 chore(components): use the post-collapsible-trigger within the post-accordion-item
  packages/components/src/components/post-accordion-item/post-accordion-item.tsx
  packages/components/src/components/post-accordion-item/readme.md
  packages/components/src/components/post-collapsible-trigger/post-collapsible-trigger.tsx
  packages/components/src/components/post-collapsible-trigger/readme.md
  packages/components/src/utils/get-root.ts
  packages/components/src/utils/index.ts
  packages/documentation/src/stories/components/collapsible/collapsible.stories.ts
Labels: v8

#3343 fix(styles): invalid CSS selector
  .changeset/four-bugs-repeat.md
  packages/styles/src/components/alert.scss
Labels: v8

#3328 feat(internet-header): improve accessibility of the search
  .changeset/beige-onions-raise.md
  packages/internet-header/src/assets/i18n/translations.ts
  packages/internet-header/src/components/post-search/post-search.tsx
Labels: v8
