Repository swisspost/design-system, pull requests merged in 2025-01, with the labels that each got.

#4427 chore(styles): remove vr helper class
  .changeset/hot-lizards-dance.md
  packages/documentation/src/stories/misc/migration-guide/migrationv8-9.component.ts
  packages/styles/src/themes/bootstrap/_utilities.scss
Labels: 🚂 PR train

#4428 chore(styles): remove stretched-link helper class
  .changeset/chilly-carrots-explain.md
  packages/documentation/src/stories/misc/migration-guide/migrationv8-9.component.ts
  packages/styles/src/themes/bootstrap/_utilities.scss
Labels: 🚂 PR train

#4429 chore(styles): remove stacks helper class
  .changeset/twelve-dodos-breathe.md
  packages/documentation/src/stories/misc/migration-guide/migrationv8-9.component.ts
  packages/styles/src/themes/bootstrap/_utilities.scss
Labels: 🚂 PR train

#4434 chore(styles): remove ratios helper class
  .changeset/sixty-clouds-cough.md
  packages/documentation/src/stories/misc/migration-guide/migrationv8-9.component.ts
  packages/styles/src/themes/bootstrap/_utilities.scss
Labels: 🚂 PR train

#4435 chore(styles): remove icon-link helper class
  .changeset/curly-insects-breathe.md
  packages/documentation/src/stories/misc/migration-guide/migrationv8-9.component.ts
  packages/styles/src/themes/bootstrap/_utilities.scss
Labels: 🚂 PR train

#4443 chore(styles, documentation): move clearfix bootstrap class to DS
  .changeset/nine-rocks-carry.md
  packages/documentation/src/stories/utilities/float/float.docs.mdx
  packages/documentation/src/stories/utilities/float/float.stories.ts
  packages/styles/src/helpers/_index.scss
  packages/styles/src/helpers/clearfix.scss
  packages/styles/src/themes/bootstrap/_utilities.scss
Labels: 🚂 PR train

#4481 chore(icons): :point_up: update icons
  .changeset/tasty-beans-knock.md
  packages/icons/src/icons/post/2634.svg
  packages/icons/src/icons/post/2635.svg
  packages/icons/src/icons/post/2636.svg
  packages/icons/src/icons/post/2637.svg
  packages/icons/src/icons/post/2638.svg
  packages/icons/src/icons/post/2639.svg
  packages/icons/src/icons/post/2640.svg
  packages/icons/src/icons/post/2641.svg
  packages/icons/src/icons/post/report.json
Labels: v9

#4421 fix(component): remove `post-popovercontainer` from `post-megadropdown`
  .changeset/fair-llamas-battle.md
  .changeset/hungry-balloons-sin.md
  packages/components/src/components.d.ts
  packages/components/src/components/post-header/post-header.scss
  packages/components/src/components/post-mainnavigation/post-mainnavigation.scss
  packages/components/src/components/post-megadropdown-trigger/post-megadropdown-trigger.scss
  packages/components/src/components/post-megadropdown-trigger/post-megadropdown-trigger.tsx
  packages/components/src/components/post-megadropdown/post-megadropdown.scss
  packages/components/src/components/post-megadropdown/post-megadropdown.tsx
  packages/components/src/components/post-megadropdown/readme.md
  packages/components/src/components/post-popovercontainer/readme.md
  packages/documentation/src/stories/raw-components/megadropdown/megadropdown.stories.ts
  packages/styles/src/components/header/_mixins.scss
  packages/styles/src/variables/_commons.scss
Labels: Header

#3986 chore: publish package with provenance
  .github/workflows/release.yaml
  .npmrc
Labels: on hold
