Repository swisspost/design-system, pull requests merged in 2025-02, with the labels that each got.

#4367 fix(components, documentation): z-index on header + fake content on header preview
  .changeset/nervous-mangos-rule.md
  .changeset/tough-bikes-punch.md
  packages/components/src/components/post-header/post-header.scss
  packages/documentation/.storybook/styles/preview.scss
  packages/documentation/src/stories/components/back-to-top/back-to-top.stories.ts
  packages/documentation/src/stories/modules/header/header.docs.mdx
  packages/documentation/src/stories/modules/header/header.scss
  packages/documentation/src/stories/modules/header/header.stories.ts
  packages/documentation/src/stories/raw-components/internet-header/header.scss
  packages/documentation/src/stories/raw-components/internet-header/header.stories.ts
  packages/documentation/src/utils/fake-content.ts
  packages/documentation/src/utils/index.ts
  packages/styles/src/components/header/index.scss
Labels: Header

#4628 fix(components): fix how the post-icon component creates the svg url
  .changeset/serious-chefs-exercise.md
  packages/components/cypress/e2e/icon.cy.ts
  packages/components/src/components/post-icon/post-icon.tsx
  packages/documentation/src/stories/components/icons/icon.snapshot.stories.ts
Labels: v7

#4624 fix(components): fix how the post-icon component creates the svg url
  .changeset/serious-chefs-exercise.md
  packages/components/cypress/e2e/icon.cy.ts
  packages/components/src/components/post-icon/post-icon.tsx
  packages/documentation/src/stories/components/icons/icon.snapshot.stories.ts
Labels: v8

#4706 chore(components): new version of `post-language-switch` (list variant)
  .changeset/fast-humans-jog.md
  packages/components/src/components/post-language-option/post-language-option.scss
  packages/components/src/components/post-language-switch/post-language-switch.scss
  packages/components/src/components/post-language-switch/post-language-switch.tsx
Labels: Header

#4723 fix(components): remove animation when switching between megadropdowns
  .changeset/shaggy-suns-suffer.md
  packages/components/src/components.d.ts
  packages/components/src/components/post-megadropdown-trigger/post-megadropdown-trigger.tsx
  packages/components/src/components/post-megadropdown/post-megadropdown.tsx
  packages/components/src/components/post-megadropdown/readme.md
Labels: Header

#4725 chore(components): switch from thrown to logged errors on `post-list`
  .changeset/swift-shrimps-dream.md
  packages/components/src/components/post-list/post-list.tsx
Labels: Header

#4694 fix(components): layout shift on active element in main navigation
  .changeset/gentle-ads-end.md
  packages/components/src/components/post-mainnavigation/post-mainnavigation.scss
  packages/components/src/components/post-mainnavigation/post-mainnavigation.tsx
Labels: Header

#4666 chore(components): add tests for the post-mainnavigation
  .changeset/tricky-foxes-check.md
  packages/components/cypress/e2e/mainnavigation.cy.ts
  packages/components/cypress/fixtures/post-mainnavigation.test.html
  packages/components/src/components/post-mainnavigation/post-mainnavigation.scss
  packages/components/src/components/post-mainnavigation/post-mainnavigation.tsx
  packages/styles/src/components/header/index.scss
Labels: Header

#4746 chore(components): update header height property
  .changeset/rich-snakes-happen.md
  .changeset/silver-bananas-kiss.md
  packages/components/src/components/post-header/post-header.tsx
  packages/styles/src/components/header/index.scss
Labels: Header

#4661 fix(component): refactor `post-menu` and `post-menu-trigger` for correct aria-expanded attribute handling
  .changeset/clever-cups-search.md
  packages/components/cypress/e2e/menu-button.cy.ts
  packages/components/src/components/post-menu-trigger/post-menu-trigger.tsx
  packages/components/src/components/post-menu/post-menu.tsx
Labels: 🐞 bug, Header

#4739 chore(components): increase gap between title and controls in `post-header`
  .changeset/chatty-toes-shop.md
  packages/components/src/components/post-header/post-header.scss
  packages/styles/src/components/header/index.scss
Labels: Header

#4747 fix(components): update from `vh` to `dvh` in `post-header` to take iOS devices into account
  .changeset/nervous-rice-fly.md
  packages/components/src/components/post-header/post-header.scss
  packages/components/src/components/post-megadropdown/post-megadropdown.scss
Labels: Header

#4757 fix(styles): fix misaligned second level navigation in the `post-megadropdown`component on desktop
  .changeset/chatty-waves-repeat.md
  packages/components/src/components/post-mainnavigation/post-mainnavigation.scss
Labels: Header

#4769 fix(styles): add height to not yet hydrated header
  .changeset/tender-glasses-arrive.md
  packages/styles/src/components/header/index.scss
Labels: Header

#4766 fix(components): correctly hide main navigation scroll arrows
  .changeset/eight-ants-warn.md
  packages/components/cypress/e2e/mainnavigation.cy.ts
  packages/components/cypress/fixtures/post-mainnavigation-overflow.test.html
  packages/components/cypress/fixtures/post-mainnavigation.test.html
  packages/components/src/components/post-mainnavigation/post-mainnavigation.scss
Labels: Header

#4738 chore(documentation): fix mobile header navigation bug in storybook
  .changeset/plenty-melons-brake.md
  packages/components/src/components/post-header/post-header.tsx
  packages/documentation/src/stories/modules/header/header.stories.ts
  packages/documentation/src/stories/modules/header/header.styles.scss
Labels: Header

#4751 fix(components): fix the bug with shifting the `post-language-switch` dropdown to the right on language selection
  .changeset/clean-cherries-tickle.md
  packages/components/src/components/post-language-switch/post-language-switch.tsx
Labels: Header

#4704 fix(component): prevent slide-down animation for already open `post-megadropdown` component when resizing from mobile/tablet to desktop
  .changeset/large-poems-dream.md
  packages/components/src/components.d.ts
  packages/components/src/components/post-megadropdown/post-megadropdown.tsx
  packages/components/src/components/post-megadropdown/readme.md
Labels: Header

#4777 chore(components): fixed the scrolling behaviour in `post-mainnavigation` to show all the nav items correctly
  .changeset/funny-goats-walk.md
  packages/components/cypress/e2e/mainnavigation.cy.ts
  packages/components/src/components/post-mainnavigation/post-mainnavigation.scss
  packages/components/src/components/post-mainnavigation/post-mainnavigation.tsx
Labels: Header

#4765 feat(component): Implement auto-closing behavior for `post-megadropdown` and `post-mainnavigation` when clicking a link inside them
  .changeset/nervous-months-smash.md
  packages/components/src/components/post-header/post-header.tsx
Labels: Header

#4788 fix: language switch send initial active event
  .changeset/real-shrimps-travel.md
  packages/components/src/components.d.ts
  packages/components/src/components/post-language-option/post-language-option.tsx
  packages/components/src/components/post-language-option/readme.md
  packages/components/src/components/post-language-switch/post-language-switch.tsx
  packages/components/src/index.html
Labels: Header

#4783 fix(styles, components): update the icon sizes in the `post-header` and `post-language-switch` components to match the design specs
  .changeset/metal-points-shave.md
  packages/components/src/components/post-language-switch/post-language-switch.scss
  packages/styles/src/components/header/index.scss
Labels: Header

#4786 fix(components): fix `post-header` scrollParent, event binding removals and calculation of the `--local-header-height` custom property
  .changeset/short-parents-lay.md
  .changeset/silly-dryers-cough.md
  .changeset/weak-lions-rest.md
  packages/components/cypress/e2e/mainnavigation.cy.ts
  packages/components/src/animations/slide.ts
  packages/components/src/components/post-back-to-top/post-back-to-top.tsx
  packages/components/src/components/post-header/post-header.scss
  packages/components/src/components/post-header/post-header.tsx
  packages/components/src/components/post-mainnavigation/post-mainnavigation.scss
  packages/documentation/src/stories/modules/header/header.styles.scss
  packages/styles/src/components/header/index.scss
Labels: Header

#4782 chore(components): move styles from `h1` to `slot=title` on `post-header`
  .changeset/real-points-deliver.md
  packages/components/cypress/e2e/mainnavigation.cy.ts
  packages/components/src/components/post-header/post-header.scss
  packages/styles/src/components/header/index.scss
Labels: Header
